//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmailServerDBEntities : DbContext
    {
        public EmailServerDBEntities()
            : base("name=EmailServerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<InboxMessage> InboxMessages { get; set; }
        public DbSet<Label> Labels { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
    }
}
