//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InboxAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InboxMessage
    {
        public int Id { get; set; }
        public System.Guid UserId { get; set; }
        public string Message { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public bool Deleted { get; set; }
        public Nullable<int> LabelId { get; set; }
        public System.DateTime DateReceived { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
